SELECT owner, table_name 
FROM dba_tables a
WHERE a.owner NOT IN ('DBSNMP','TRACESVR','AURORA$ORB$UNAUTHENTICATED','AURORA$JIS$UTILITY$','OLAPSYS',
 'OSE$HTTP$ADMIN','MDSYS','ORDSYS','ORDPLUGINS','SI_INFORMTN_SCHEMA','CTXSYS','SYSMAN',
 'WKSYS','WKUSER','WK_TEST','REPADMIN','LBACSYS','DVF','DVSYS','ODM','ODM_MTR','DMSYS',
 'WMSYS','ANONYMOUS','XDB','EXFSYS','DIP','SYS','SYSTEM','ORDDATA','OUTLN','APPQOSSYS',
 'XS$NULL','ORACLE_OCM','DBADMIN','BL','IDM','GGSMGR','OPS$ORACLE')
and a.owner NOT LIKE 'APEX%'
and a.owner NOT LIKE 'FLOWS_%'
 AND NOT EXISTS (
  SELECT 
      owner, 
      table_name 
  FROM DBA_LOG_GROUPS b
  WHERE a.owner = b.owner AND a.table_name = b.table_name);
  
  
col owner for a16
col db_link for a20
col username for a16
col host for a60
set lines 120

select owner, db_link, username, host, created from dba_db_links order by owner;


CREATE MATERIALIZED VIEW ioweb.PEOPLEBOOK ("USER_ID", "SAP_ID", "COUNTRY", "NAME", "INTERNAL_PHONE", "PHONE", "MOBILE", "SUPPORT_PHONE", "FAX", "EMAIL", "LOCATION", "POSTAL_CODE", "POSTAL_ADDRESS", "OFFICE_ADDRESS", "LOADED_DATE")
  ORGANIZATION HEAP
 NOCOMPRESS LOGGING
  TABLESPACE "IOWEB_T"
  BUILD DEFERRED
  USING INDEX
  TABLESPACE "IOWEB_I"
  REFRESH COMPLETE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT USER_ID,SAP_ID,COUNTRY,NAME,INTERNAL_PHONE,PHONE,MOBILE,SUPPORT_PHONE,FAX,EMAIL,LOCATION,POSTAL_CODE,POSTAL_ADDRESS,OFFICE_ADDRESS,LOADED_DATE FROM WEB.PEOPLEBOOK@BLD;

 